-- ============================================================
-- Production SQL — speakers + program_items
-- Généré le 2026-07-14 14:02:55
-- À exécuter sur le serveur de production (ugfa-ev.org)
-- ============================================================

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- Vider d'abord la table enfant (program_items référence speakers via fk_program_speaker)
TRUNCATE TABLE program_items;

-- Speakers (DELETE au lieu de TRUNCATE : phpMyAdmin réinitialise la session entre chaque requête,
-- TRUNCATE échoue même avec FK vides car la contrainte existe au niveau schéma)
DELETE FROM speakers;
INSERT INTO speakers (id, full_name, title, organization, bio, photo_path, is_featured, created_at, updated_at) VALUES (4, 'Kabiné Komara', 'Ancien Premier Ministre de la République de Guinée', 'Comité Stratégique Simandou 2040', 'Intervenant sur les aspects institutionnels du Programme Simandou 2040 et son impact pour la diaspora guinéenne.', 'assets/images/speakers/kabine_komara.jpg', 1, '2026-07-05 17:13:19', '2026-07-05 17:13:19');
INSERT INTO speakers (id, full_name, title, organization, bio, photo_path, is_featured, created_at, updated_at) VALUES (5, 'Bernard Goumou', 'Ancien Premier Ministre de la République de Guinée', 'Comité Stratégique Simandou 2040', 'Intervenant sur les aspects entrepreneuriaux et les opportunités d\'investissement dans le cadre du Programme Simandou 2040.', 'assets/images/speakers/bernard_goumou.jpg', 1, '2026-07-05 17:13:19', '2026-07-05 17:13:19');
INSERT INTO speakers (id, full_name, title, organization, bio, photo_path, is_featured, created_at, updated_at) VALUES (6, 'Saran Daraba Kaba', 'Ancienne Ministre de la République de Guinée', 'Comité Stratégique Simandou 2040', 'Intervenante sur les aspects genre et la participation féminine dans le contexte du développement durable de la Guinée.', 'assets/images/speakers/hadja_saran_daraba_kaba.jpg', 1, '2026-07-05 17:13:19', '2026-07-05 17:13:19');
INSERT INTO speakers (id, full_name, title, organization, bio, photo_path, is_featured, created_at, updated_at) VALUES (7, 'Prof. Siba N\'Zatioula Grovogui', 'Professeur de Relations Internationales', 'Université Johns Hopkins', 'Expert des aspects juridiques, éthiques et de la promotion de la paix dans le cadre du Programme Simandou 2040.', 'assets/images/speakers/grovogui.jpg', 1, '2026-07-05 17:13:19', '2026-07-05 17:13:19');
INSERT INTO speakers (id, full_name, title, organization, bio, photo_path, is_featured, created_at, updated_at) VALUES (8, 'Mohamed Beavogui', 'Ancien Sous-Secrétaire Général des Nations-Unies', 'Nations-Unies', 'Expert en développement international, intervenant sur la contribution de la diaspora guinéenne au développement local et modérateur du panel des autorités municipales.', 'assets/images/speakers/mohamed_beavogui.jpg', 1, '2026-07-05 17:13:19', '2026-07-05 17:13:19');
INSERT INTO speakers (id, full_name, title, organization, bio, photo_path, is_featured, created_at, updated_at) VALUES (9, 'Rose Pola Pricemou', 'Conseillère à la Présidence de la République de Guinée', 'Présidence de la République de Guinée', 'Intervenante sur la dimension coopération spécifique entre la diaspora guinéenne et son pays d\'origine.', 'assets/images/speakers/rose_pola_pricemou.webp', 1, '2026-07-05 17:13:19', '2026-07-05 18:27:55');
INSERT INTO speakers (id, full_name, title, organization, bio, photo_path, is_featured, created_at, updated_at) VALUES (10, 'Dr. Boubacar Sidy Sow', 'Docteur en Sciences Sociales', 'Réseau Diaspora Guinée-Allemagne', 'Spécialiste de l\'intégration et de la recherche de partenaires dans les pays d\'accueil de la diaspora guinéenne.', NULL, 1, '2026-07-05 17:13:19', '2026-07-05 17:13:19');
INSERT INTO speakers (id, full_name, title, organization, bio, photo_path, is_featured, created_at, updated_at) VALUES (11, 'Verena Schäffer', 'Ministre des Enfants, de la Jeunesse, de la Famille, de l\'Égalité, des Réfugiés et de l\'Intégration', 'Land Rhénanie-du-Nord-Westphalie', 'Intervenante principale lors de la cérémonie de clôture du Projet Ankoppeln, présentant le bilan et les perspectives du projet.', 'assets/images/speakers/verena_schaffer.jpg', 1, '2026-07-05 17:13:19', '2026-07-05 17:13:19');
INSERT INTO speakers (id, full_name, title, organization, bio, photo_path, is_featured, created_at, updated_at) VALUES (12, 'Patriarche Goikoya-Lambert Zogbelemou', 'Patriarche de la communauté Guinée Forestière', 'Délégation du Patriarche', 'Représentant des aspects communautaires et traditionnels dans le dialogue interculturel et la coopération internationale.', 'assets/images/speakers/patriarche_goikoya-lambert_zogbelemou.jpg', 1, '2026-07-05 17:13:19', '2026-07-05 18:30:32');

-- Program items
INSERT INTO program_items (id, event_date, start_time, end_time, title_fr, title_de, description_fr, description_de, location, item_type, speaker_id, speakers_list, display_order, is_active, created_at, updated_at) VALUES (59, '2026-10-03', '16:00:00', '00:00:00', 'Grillade, Networking et soirée dansante', 'Grillfest, Networking und Tanzabend', '16H–16H50 : Associations guinéennes – Mode vestimentaire comme facteur d\'intégration culturelle et défilé de mode en tenues nationales guinéennes.
17H–18H : Grillade et Networking Afrique-Allemagne.
21H–? : Soirée récréative et dansante avec la musique comme facteur d\'intégration culturelle.', '16H–16H50 : Guineische Vereine – Bekleidungsstil als Faktor kultureller Integration und Modenschau in traditioneller guineischer Kleidung.
17H–18H : Grillfest und Afrika-Deutschland-Networking.
21H–? : Geselliger Tanzabend mit Musik als Faktor kultureller Integration.', NULL, 'networking', NULL, NULL, 0, 1, '2026-07-05 18:42:53', '2026-07-05 18:42:53');
INSERT INTO program_items (id, event_date, start_time, end_time, title_fr, title_de, description_fr, description_de, location, item_type, speaker_id, speakers_list, display_order, is_active, created_at, updated_at) VALUES (47, '2026-10-01', '10:00:00', '21:00:00', 'Accueil des délégations et invités spéciaux', 'Empfang der Delegationen und Ehrengäste', 'Arrivée et installation des invités, suivies d\'un dîner de bienvenue pour ouvrir la Semaine de Dialogue et de Coopération Internationale.', 'Ankunft und Unterbringung der Gäste, gefolgt von einem Begrüßungsessen zum Auftakt der Woche des Dialogs und der internationalen Zusammenarbeit.', 'Leonie-Reygers-Terrasse, 44137 Dortmund', 'ceremony', NULL, 'Comité d\'organisation — Arrivée et installation des invités (10H–18H)
Comité d\'organisation — Dîner de bienvenue (19H)', 1, 1, '2026-07-05 16:31:10', '2026-07-05 16:31:10');
INSERT INTO program_items (id, event_date, start_time, end_time, title_fr, title_de, description_fr, description_de, location, item_type, speaker_id, speakers_list, display_order, is_active, created_at, updated_at) VALUES (48, '2026-10-02', '10:00:00', '15:00:00', 'Cérémonie de clôture du Projet Ankoppeln', 'Abschlussveranstaltung des Projekts Ankoppeln', 'Intervention de la Ministre des Enfants, de la Jeunesse, de la Famille, de l\'Égalité, des Réfugiés et de l\'Intégration de Rhénanie-du-Nord-Westphalie sur le bilan et les perspectives du projet Ankoppeln.', 'Rede der Ministerin für Kinder, Jugend, Familie, Gleichstellung, Flüchtlinge und Integration des Landes Nordrhein-Westfalen zu Bilanz und Perspektiven des Projekts Ankoppeln.', 'Leonie-Reygers-Terrasse, 44137 Dortmund', 'ceremony', NULL, 'Mme Verena Schäffer, Ministre NRW — Bilan et Perspectives du Projet Ankoppeln
Comité d\'organisation — Pause-Buffet (14H–15H)', 2, 1, '2026-07-05 16:31:10', '2026-07-05 16:31:10');
INSERT INTO program_items (id, event_date, start_time, end_time, title_fr, title_de, description_fr, description_de, location, item_type, speaker_id, speakers_list, display_order, is_active, created_at, updated_at) VALUES (49, '2026-10-02', '15:00:00', '18:00:00', 'Programme Simandou 2040 et Opportunités d\'Investissement des Entreprises Étrangères (Allemandes)', 'Programm Simandou 2040 und Investitionsmöglichkeiten für ausländische (deutsche) Unternehmen', 'Présentation du cadre général et des enjeux du Programme Simandou 2040 pour la diaspora guinéenne, suivie d\'un panel d\'anciens Premiers ministres et d\'experts guinéens.', 'Vorstellung des allgemeinen Rahmens und der Herausforderungen des Programms Simandou 2040 für die guineische Diaspora, gefolgt von einem Panel ehemaliger Premierminister und guineischer Experten.', 'Leonie-Reygers-Terrasse, 44137 Dortmund', 'panel', NULL, 'Ministre Directeur Cabinet Présidence — Président Comité Stratégique Simandou 2040
M. Kabiné Komara, Ancien Premier Ministre — Aspects Institutionnels du Programme 2040
M. Bernard Goumou, Ancien Premier Ministre — Aspects Entrepreneuriaux et Investissements
Mme Saran Daraba Kaba, Ancienne Ministre — Aspects Genre et participation féminine
Prof. Siba N\'Zatioula Grovogui — Aspects Juridiques, Éthiques et Promotion de la Paix', 3, 1, '2026-07-05 16:31:10', '2026-07-05 16:31:10');
INSERT INTO program_items (id, event_date, start_time, end_time, title_fr, title_de, description_fr, description_de, location, item_type, speaker_id, speakers_list, display_order, is_active, created_at, updated_at) VALUES (50, '2026-10-03', '13:00:00', '15:00:00', 'Intégration de la Diaspora guinéenne en Allemagne et contribution au développement durable dans le contexte Simandou 2040', 'Integration der guineischen Diaspora in Deutschland und ihr Beitrag zur nachhaltigen Entwicklung im Rahmen von Simandou 2040', 'Panel sur les axes de coopération avec l\'État guinéen, suivi d\'un défilé de mode traditionnelle, d\'un networking Afrique-Allemagne et d\'une soirée culturelle dansante.', 'Podiumsdiskussion zu den Kooperationsschwerpunkten mit dem guineischen Staat, gefolgt von einer traditionellen Modenschau, einem Afrika-Deutschland-Networking und einem kulturellen Tanzabend.', 'Leonie-Reygers-Terrasse, 44137 Dortmund', 'panel', NULL, 'M. Mohamed Beavogui, Ancien Fonctionnaire Nations Unies — Contribution diaspora au développement local
Mme Rose Pola Pricemou, Conseillère à la Présidence en Guinée — Coopération diaspora-pays d\'origine
Patriarche Goikoya-Lambert Zogbelemou et sa délégation — Aspects Communautaires
Dr. Boubacar Sidy Sow — Intégration et recherche de partenaires dans les pays d\'accueil de la diaspora', 4, 1, '2026-07-05 16:31:10', '2026-07-05 16:31:10');
INSERT INTO program_items (id, event_date, start_time, end_time, title_fr, title_de, description_fr, description_de, location, item_type, speaker_id, speakers_list, display_order, is_active, created_at, updated_at) VALUES (51, '2026-10-04', '13:00:00', '18:00:00', 'Visite touristique dans la ville de Dortmund pour émulation au développement local de la Guinée Forestière', 'Touristischer Rundgang durch Dortmund als Inspiration für die lokale Entwicklung der Waldregion Guineas', 'Visite du musée du football de Dortmund par la délégation du Patriarche et les invités spéciaux.', 'Besuch des Fußballmuseums Dortmund durch die Delegation des Patriarchen und die Ehrengäste.', 'Leonie-Reygers-Terrasse, 44137 Dortmund', 'exhibition', NULL, 'Délégation du Patriarche Goikoya-Lambert Zogbelemou
Invités spéciaux', 5, 1, '2026-07-05 16:31:10', '2026-07-05 16:31:10');
INSERT INTO program_items (id, event_date, start_time, end_time, title_fr, title_de, description_fr, description_de, location, item_type, speaker_id, speakers_list, display_order, is_active, created_at, updated_at) VALUES (52, '2026-10-05', '10:00:00', '18:00:00', 'Recherche de partenariat d\'affaires avec les entreprises Allemandes dans le cadre Simandou 2040', 'Suche nach Geschäftspartnerschaften mit deutschen Unternehmen im Rahmen von Simandou 2040', 'Visite d\'une première entreprise à fort potentiel d\'investissement, exposition culturelle guinéenne et entretien spécial avec les femmes et enfants sur l\'intégration.', 'Besuch eines ersten Unternehmens mit hohem Investitionspotenzial, kulturelle Ausstellung Guineas und ein besonderes Gespräch mit Frauen und Kindern über Integration.', 'Leonie-Reygers-Terrasse, 44137 Dortmund', 'networking', NULL, 'Comité d\'organisation
Délégation du Patriarche et invités spéciaux', 6, 1, '2026-07-05 16:31:10', '2026-07-05 16:31:10');
INSERT INTO program_items (id, event_date, start_time, end_time, title_fr, title_de, description_fr, description_de, location, item_type, speaker_id, speakers_list, display_order, is_active, created_at, updated_at) VALUES (53, '2026-10-06', '10:00:00', '18:00:00', 'Simandou 2040 et Opportunités d\'affaires en Guinée pour les Entreprises Allemandes', 'Simandou 2040 und Geschäftsmöglichkeiten in Guinea für deutsche Unternehmen', 'Visite d\'une deuxième entreprise à fort potentiel d\'investissement, exposition culturelle et entretien avec les jeunes africains sur leur intégration en Allemagne.', 'Besuch eines zweiten Unternehmens mit hohem Investitionspotenzial, kulturelle Ausstellung und Gespräch mit jungen Afrikanern über ihre Integration in Deutschland.', 'Leonie-Reygers-Terrasse, 44137 Dortmund', 'conference', NULL, 'Comité d\'organisation
Comité d\'organisation / Expert Intégration', 7, 1, '2026-07-05 16:31:10', '2026-07-05 16:31:10');
INSERT INTO program_items (id, event_date, start_time, end_time, title_fr, title_de, description_fr, description_de, location, item_type, speaker_id, speakers_list, display_order, is_active, created_at, updated_at) VALUES (54, '2026-10-07', '10:00:00', '18:00:00', 'Simandou 2040 et Aspects Environnementaux en Guinée', 'Simandou 2040 und Umweltaspekte in Guinea', 'Visite d\'une institution ou ONG écologique pour un partenariat sur l\'adaptation aux changements climatiques, exposition culturelle et entretien avec les jeunes professionnels.', 'Besuch einer ökologischen Institution oder NGO für eine Partnerschaft zur Anpassung an den Klimawandel, kulturelle Ausstellung und Gespräch mit jungen Berufstätigen.', 'Leonie-Reygers-Terrasse, 44137 Dortmund', 'conference', NULL, 'Comité d\'organisation
Comité d\'organisation / Expert Entrepreneuriat Allemand', 8, 1, '2026-07-05 16:31:10', '2026-07-05 16:31:10');
INSERT INTO program_items (id, event_date, start_time, end_time, title_fr, title_de, description_fr, description_de, location, item_type, speaker_id, speakers_list, display_order, is_active, created_at, updated_at) VALUES (55, '2026-10-08', '10:00:00', '18:00:00', 'Recherche de Partenariat avec un Centre de Formation en Allemagne et Lutte contre l\'Immigration Clandestine des Jeunes en Guinée — Simandou 2040', 'Suche nach einer Partnerschaft mit einem Ausbildungszentrum in Deutschland und Bekämpfung der irregulären Migration junger Menschen in Guinea — Simandou 2040', 'Visite d\'un centre de formation pour ouvriers, techniciens et ingénieurs, exposition culturelle et entretien avec les responsables d\'associations guinéennes.', 'Besuch eines Ausbildungszentrums für Arbeiter, Techniker und Ingenieure, kulturelle Ausstellung und Gespräch mit Verantwortlichen guineischer Vereine.', 'Leonie-Reygers-Terrasse, 44137 Dortmund', 'workshop', NULL, 'Comité d\'organisation
Comité d\'organisation / Expert en réseautage et échange d\'expériences des associations', 9, 1, '2026-07-05 16:31:10', '2026-07-05 16:31:10');
INSERT INTO program_items (id, event_date, start_time, end_time, title_fr, title_de, description_fr, description_de, location, item_type, speaker_id, speakers_list, display_order, is_active, created_at, updated_at) VALUES (56, '2026-10-09', '10:00:00', '18:00:00', 'Prise de contact avec les autorités municipales et Panel de lutte contre la Pauvreté en Guinée Forestière dans le Contexte Simandou 2040', 'Kontaktaufnahme mit den städtischen Behörden und Podiumsdiskussion zur Armutsbekämpfung in der Waldregion Guineas im Kontext von Simandou 2040', 'Visite de la mairie de Dortmund en vue d\'un jumelage, panel sur l\'agriculture et les énergies durables, et interventions d\'entrepreneurs guinéens modèles en Allemagne.', 'Besuch des Dortmunder Rathauses im Hinblick auf eine Städtepartnerschaft, Podiumsdiskussion zu Landwirtschaft und nachhaltiger Energie sowie Beiträge erfolgreicher guineischer Unternehmer in Deutschland.', 'Leonie-Reygers-Terrasse, 44137 Dortmund', 'panel', NULL, 'M. Mohamed Beavogui, Ancien Sous-Secrétaire Général des Nations-Unies — Modérateur
Maire de Dortmund
Maire de Nzérékoré
Un Représentant d\'ONG Écologique
Un Représentant d\'une Institution de Développement durable
Prof. Siba N\'Zatioula Grovogui — Organisation communautaire
Top modèles entrepreneurs guinéens en Allemagne', 10, 1, '2026-07-05 16:31:10', '2026-07-05 16:31:10');
INSERT INTO program_items (id, event_date, start_time, end_time, title_fr, title_de, description_fr, description_de, location, item_type, speaker_id, speakers_list, display_order, is_active, created_at, updated_at) VALUES (57, '2026-10-10', '10:00:00', '18:00:00', 'Visite touristique au Sauerland pour émulation de développement en Guinée Forestière', 'Touristischer Ausflug ins Sauerland als Inspiration für die Entwicklung der Waldregion Guineas', 'Visite du Sauerland comme source d\'inspiration pour le développement du tourisme en Guinée Forestière, suivie de l\'évaluation des activités et de la production des livrables de l\'événement.', 'Besuch des Sauerlands als Inspirationsquelle für den Tourismus in der Waldregion Guineas, gefolgt von der Auswertung der Aktivitäten und der Erstellung der Veranstaltungsergebnisse.', 'Leonie-Reygers-Terrasse, 44137 Dortmund', 'exhibition', NULL, 'Comité d\'organisation', 11, 1, '2026-07-05 16:31:10', '2026-07-05 16:31:10');
INSERT INTO program_items (id, event_date, start_time, end_time, title_fr, title_de, description_fr, description_de, location, item_type, speaker_id, speakers_list, display_order, is_active, created_at, updated_at) VALUES (58, '2026-10-11', NULL, NULL, 'Préparatifs de retour des invités', 'Vorbereitungen für die Rückreise der Gäste', 'Organisation du retour de la délégation du Patriarche et des invités spéciaux.', 'Organisation der Rückreise der Delegation des Patriarchen und der Ehrengäste.', 'Leonie-Reygers-Terrasse, 44137 Dortmund', 'ceremony', NULL, 'Comité d\'organisation — Retour de la délégation du Patriarche et des Invités spéciaux (Horaire flexible)', 12, 1, '2026-07-05 16:31:10', '2026-07-05 16:31:10');

SET FOREIGN_KEY_CHECKS = 1;

-- Fin du script